import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import styles from "./style";

import { NavbarComponent, FooterComponent, BodyComponent, HeroComponent, CTA } from "@/components";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-primary w-full overflow-hidden">
          <div className={`${styles.paddingX} ${styles.flexCenter}`}>
            <div className={`${styles.boxWidth}`}>
              <NavbarComponent></NavbarComponent>
            </div>
          </div>

          <div className={`bg-primary  ${styles.paddingX} ${styles.flexCenter} ${styles.fullHeight} `}>
            <div className={`${styles.boxWidth} `}>
              <BodyComponent>{children}</BodyComponent>
            </div>
          </div>

          <div className={`bg-primary ${styles.paddingX} ${styles.flexCenter}`}>
            <div className={`${styles.boxWidth}`}>
              <FooterComponent />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
